### ISSUE TITLE
[Bug] Mismatch of token names between backend and tracker

### ISSUE THREAD

**Issue by Zorlin** [torrust/torrust#24]
Hi there,

When you run the tracker with no config file, it generates a config file with the following token:
admin = "MyAccessToken"

However, when you run the backend with no config file, it generates a config file which references the following token:
token = "MyAccessToken"

They should ideally match, ie both be "token" or both be "admin".

**Comment by WarmBeer** [comment]
The tracker can hold multiple access tokens. `admin = "MyAccessToken"` is just an example.
