### ISSUE TITLE
ansible-torrust-installer nginx gives 413 Request Entity Too Large

### ISSUE THREAD

**Issue by pimors** [torrust/torrust#26]
When uploading a torrent where the content is large (around 40gb) nginx gives the 413 error. I'm not sure if the website or the sever is the problem. The torrent file itself is around 3.6mb big.

**Comment by pimors** [comment]
sorry figured it out. Nginx has the default size limit.

**Comment by Zorlin** [comment]
Hi @pimors,

We should potentially set a higher size limit in nginx by default. I'll look into it.
