### ISSUE TITLE
upload button misses when browser window is smaller

### ISSUE THREAD

**Issue by pimors** [torrust/torrust#27]
When the browser window is smaller, like for example when it is not fullscreen, the upload button disappears.
![browser-fullscreen-torrust](https://user-images.githubusercontent.com/80458099/157012868-bbeee5fd-66ed-432b-94e8-c19059dbeac5.png)
![browser-smaller-torrust](https://user-images.githubusercontent.com/80458099/157012871-7fb09efe-25eb-4da3-baf8-fcbeda41717b.png)

**Comment by WarmBeer** [comment]
On mobile the upload button gets moved to the mobile menu/sidebar :)

**Comment by pimors** [comment]
Either something is wrong with my configuration or that's not true. When i make the windows so small that the upload button disappears it doesn't show up in the burger menu. It is just gone until I make the windows big enough.
