### ISSUE TITLE
Config setting to enable/disable emails

### ISSUE THREAD

**Issue by rakema01** [torrust/torrust#32]
Would like to see a setting to enable or disable emails for account creation. Email verification is nice for private trackers, but a basic user/pass authentication method is great for semi-private trackers that want to deter its users from spreading the torrents to public forums but don't want to collect and store emails, whether due to privacy or security reasons.

**Comment by WarmBeer** [comment]
https://github.com/torrust/torrust/commit/51ba069973691bb91e7397ade0b5e5a6145d3ed5

Added the option to set email requirement during sign-up to either:  Required, Optional or None.

<img width="682" alt="Screenshot 2022-05-15 at 15 42 50" src="https://user-images.githubusercontent.com/12992260/168475983-9dd9a481-0676-46c2-bbf3-0cdfde7b6f0f.png">

None:
<img width="582" alt="Screenshot 2022-05-15 at 15 45 17" src="https://user-images.githubusercontent.com/12992260/168476080-25ccc91b-d2cd-4f46-abe3-b5f24064372a.png">
