### ISSUE TITLE
Contributor Agreement (CA)

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust#59]
Hello @WarmBeer

I have noticed that @BelieveInBunny [has proposed a significant contribution to this project!](https://github.com/torrust/torrust/pull/58) 😄

It would be great to have the contributors agree with a Contributor Agreement.  Particularly because out policy of re-licensing the old-code to [MIT-0](https://opensource.org/licenses/MIT-0) after five years of publishing.

> This kind-of works like an accelerated form of "Public Domain" where old works become freely available to everyone.

Please read this [contributor agreement](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/licensing/contributor_agreement_v01.md) that we use for [Nautilus Cyberneering](https://github.com/Nautilus-Cyberneering).

The List of Acceptable Licenses for Nautilus may be expanded to better suit the intentions of this project.

**Comment by da2ce7** [comment]
@WarmBeer If this is a good idea, we probably need to make another copy of this for the https://github.com/torrust/torrust-tracker or start storing it in a common section such as the `.github` repository, or something.

Additionally, maybe we need to think of some way where the contributors can easily agree our contributor agreement, the most elegant solution that I have seen so far is: https://pijul.org/cla ... However this is a bit-too-future-looking for now.

**Comment by da2ce7** [comment]
@cgbosse 👋

**Comment by BelieveInBunny** [comment]
Thank you very much, 
soon I will have the remaining feature finished from milestone https://github.com/torrust/torrust/milestone/1

and yes it is a good idea, I would love to contribute and agree to the terms.

**Comment by cgbosse** [comment]
Good morning @WarmBeer 
let me know if you need help.

**Comment by WarmBeer** [comment]
Hey @cgbosse ,

Do you think we need to make any changes to the CA for Torrust?

**Comment by cgbosse** [comment]
It depends on the discussion we have in our next development agreement and how Torrust is going to be displayed.
